stages:
  scrape_data:
    cmd: python -m src.scrape.scrape_data
    deps:
    - src/scrape/scrape_data.py
    outs:
    - data/raw/bios.csv
    - data/raw/results.csv
    frozen: true
  clean_athletes_bio:
    cmd: python -m src.data.clean_athletes_bio
    deps:
    - src/data/clean_athletes_bio.py
    - data/raw/bios.csv
    outs:
    - data/interim/bios.csv
  clean_athletes_results:
    cmd: python -m src.data.clean_athletes_results
    deps:
    - src/data/clean_athletes_results.py
    - data/raw/results.csv
    outs:
    - data/interim/results.csv
